# Generated by Django 4.0.3 on 2022-03-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poop_profiles', '0002_friendlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
